services:
  redis:
    image: "redis:latest"
  postgres:
    image: "postgres:16"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=grep3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grep3
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:grep3@postgres:5432/grep3
      - DOCKER_HOST=http://docker:2375
      - HOST=http://web:8080
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - WAIT_HOSTS=postgres:5432,redis:6379
    volumes:
      - ./dist:/usr/grep3/dist
