version: "3"
services:
  redis:
    image: "redis"
  postgres:
    image: "postgres:16"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=web3-compute
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=web3-compute
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:web3-compute@postgres:5432/web3-compute
      - PORT=8000
      - REDIS_URL=redis://redis:6379
      - WAIT_HOSTS=postgres:5432,redis:6379
